cat data/diccionario_a.txt | php procesador_texto.php 0 1 > resultados/res_A.txt
cat data/textos/letra_B.txt | php procesador_texto.php 0 303 > resultados/res_B.txt
cat data/textos/letra_C.txt | php procesador_texto.php 0 525 > resultados/res_C.txt
cat data/textos/letra_D.txt | php procesador_texto.php 0 964 > resultados/res_D.txt
cat data/textos/letra_E.txt | php procesador_texto.php 0 1073 > resultados/res_E.txt
cat data/textos/letra_F.txt | php procesador_texto.php 0 1177 > resultados/res_F.txt
cat data/textos/letra_G.txt | php procesador_texto.php 0 1303 > resultados/res_G.txt
cat data/textos/letra_H.txt | php procesador_texto.php 0 1574 > resultados/res_H.txt
cat data/textos/letra_I.txt | php procesador_texto.php 0 1663 > resultados/res_I.txt
cat data/textos/letra_J.txt | php procesador_texto.php 0 1728 > resultados/res_J.txt
cat data/textos/letra_K.txt | php procesador_texto.php 0 1784 > resultados/res_K.txt
cat data/textos/letra_L.txt | php procesador_texto.php 0 1802 > resultados/res_L.txt
cat data/textos/letra_M.txt | php procesador_texto.php 0 1999 > resultados/res_M.txt 
cat data/textos/letra_N.txt | php procesador_texto.php 0 2393 > resultados/res_N.txt 
cat data/textos/letra_O.txt | php procesador_texto.php 0 2457 > resultados/res_O.txt 
cat data/textos/letra_P.txt | php procesador_texto.php 0 2562 > resultados/res_P.txt 
cat data/textos/letra_Q.txt | php procesador_texto.php 0 2789 > resultados/res_Q.txt 
cat data/textos/letra_R.txt | php procesador_texto.php 0 2807 > resultados/res_R.txt 
cat data/textos/letra_S.txt | php procesador_texto.php 0 3085 > resultados/res_S.txt 
cat data/textos/letra_T.txt | php procesador_texto.php 0 3365 > resultados/res_T.txt 
cat data/textos/letra_U.txt | php procesador_texto.php 0 3620 > resultados/res_U.txt 
cat data/textos/letra_V.txt | php procesador_texto.php 0 3666 > resultados/res_V.txt 
cat data/textos/letra_W.txt | php procesador_texto.php 0 3827 > resultados/res_W.txt 
cat data/textos/letra_X.txt | php procesador_texto.php 0 3850 > resultados/res_X.txt 
cat data/textos/letra_Y.txt | php procesador_texto.php 0 3858 > resultados/res_Y.txt 
cat data/textos/letra_Z.txt | php procesador_texto.php 0 3873 > resultados/res_Z.txt 